# Generated by Django 5.2.8 on 2026-02-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ameneties',
            new_name='Amenities',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='ameneties',
            new_name='amenities',
        ),
    ]
